### ISSUE TITLE
编译错误，不知道咋解决

### ISSUE THREAD

**Issue by omegazero01** [TheBlindM/CK-567#1]
开始编译...
error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel
See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.

**Comment by TheBlindM** [comment]
详细看readme 环境配置这块



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月1日(周六) 下午5:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [TheBlindM/CK-567] 编译错误，不知道咋解决 (Issue #1)




 
开始编译...
 error: the -Z flag is only accepted on the nightly channel of Cargo, but this is the stable channel
 See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
