### ISSUE TITLE
ssl connect error when i use it .

### ISSUE THREAD

**Issue by 0xAcctracy** [TheBlindM/CK-567#2]
error: failed to download from `https://crates.io/api/v1/crates/rand/0.8.5/downl
oad`

Caused by:
  [35] SSL connect error (schannel: next InitializeSecurityContext failed: SEC_E
_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS a
lert is received (e.g. handshake failed). More detail may be available in the Wi
ndows System event log.)

**Comment by TheBlindM** [comment]
参考：https://www.cnblogs.com/gelare/p/12912483.html

**Comment by 0xAcctracy** [comment]
i am try to create config file in .cargo path and set CARGO_HTTP_CHECK_REVOKE=false into env are both of fail. the error as before.

**Comment by TheBlindM** [comment]
不好意思了🤣，我没遇到过，尝试google
